apiVersion: apps/v1
kind: Deployment
metadata:
  name: tactile-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tactile-platform
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tactile-platform
    spec:
      containers:
        - image: tactile-platform:latest
          name: tactile-platform
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tactile-platform-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tactile-platform
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tactile-platform-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: "tactile-platform-svc"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      real_ip_header CF-Connecting-IP;
      proxy_set_header X-Real-IP $http_cf_connecting_ip;
    cert-manager.io/cluster-issuer: "tactile3d-cloudflare-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.tactile3d.dev
      secretName: managed-api-tactile3d-dev-tls
  rules:
    - host: api.tactile3d.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tactile-platform-svc
                port:
                  number: 8080
